RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Advertising.Xaml_10.1808.3.0_x64__8wekyb3d8bbwe
RD /S /Q C:\Windows\SystemApps\Microsoft.AsyncTextService_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.BingWeather_4.25.20211.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.BingWeather_4.25.20211.0_neutral_split.scale-150_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.BingWeather_4.25.20211.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.30251.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.30251.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.30251.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_2019.125.2243.0_neutral_~_8wekyb3d8bbwe
RD /S /Q C:\Windows\SystemApps\Microsoft.ECApp_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.GetHelp_10.1706.13331.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.GetHelp_10.1706.13331.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.GetHelp_10.1706.13331.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.GetHelp_10.1706.13331.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Getstarted_7.3.20251.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Getstarted_7.3.20251.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Getstarted_7.3.20251.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.HEIFImageExtension_1.0.13472.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Messaging_2019.125.32.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Messaging_4.1901.10241.0_neutral_split.scale-150_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Messaging_4.1901.10241.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Microsoft3DViewer_5.1902.20012.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Microsoft3DViewer_5.1902.20012.0_x64__8wekyb3d8bbwe
RD /S /Q C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
RD /S /Q C:\Windows\SystemApps\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.1901.1141.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftSolitaireCollection_4.2.11280.0_x86__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_3.1.53.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_3.1.53.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_3.1.53.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_3.1.53.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MixedReality.Portal_2000.19010.1151.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MixedReality.Portal_2000.19010.1151.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MixedReality.Portal_2000.19010.1151.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MixedReality.Portal_2000.19010.1151.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MSPaint_2019.213.1858.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.MSPaint_5.1902.13017.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Office.OneNote_16001.11126.20076.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Office.OneNote_16001.11126.20076.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.OneConnect_5.1902.361.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.OneConnect_5.1902.361.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.OneConnect_5.1902.361.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.OneConnect_5.1902.361.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.People_10.1812.10232.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.People_10.1812.10232.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.People_10.1812.10232.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.People_2019.123.2346.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Print3D_3.3.311.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Print3D_3.3.311.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Print3D_3.3.311.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Print3D_3.3.311.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ScreenSketch_10.1811.3471.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ScreenSketch_10.1811.3471.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ScreenSketch_10.1811.3471.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ScreenSketch_2018.1214.231.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.StorePurchaseApp_11811.1001.18.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.StorePurchaseApp_11811.1001.18.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.StorePurchaseApp_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.VP9VideoExtensions_1.0.13333.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Wallet_2.4.18324.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WebMediaExtensions_1.0.13321.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WebMediaExtensions_1.0.13321.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WebMediaExtensions_1.0.13321.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WebMediaExtensions_1.0.13321.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WebpImageExtension_1.0.12821.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Windows\SystemApps\microsoft.windows.narratorquickstart_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2019.18114.19418.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2019.18114.19418.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2019.18114.19418.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2019.18114.19418.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsAlarms_10.1812.10043.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsAlarms_10.1812.10043.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsAlarms_10.1812.10043.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsAlarms_2019.105.629.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1812.10048.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1812.10048.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1812.10048.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_2019.105.612.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2018.826.78.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2018.826.78.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2018.826.78.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2018.826.78.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\microsoft.windowscommunicationsapps_16005.11029.20108.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\microsoft.windowscommunicationsapps_16005.11029.20108.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1811.10571.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1811.10571.0_neutral_split.scale-140_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1811.10571.0_neutral_split.scale-180_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1811.10571.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_2019.226.2324.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsMaps_2019.108.627.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsMaps_5.1812.10071.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsMaps_5.1812.10071.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsMaps_5.1812.10071.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_10.1812.10043.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_10.1812.10043.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_10.1812.10043.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_2019.105.618.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsStore_11811.1001.18.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsStore_11811.1001.18.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsStore_11811.1001.18.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.WindowsStore_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Xbox.TCUI_1.23.28002.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.Xbox.TCUI_1.23.28002.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxApp_48.48.7001.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxApp_48.48.7001.0_neutral_split.scale-200_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxApp_48.48.7001.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxApp_48.48.7001.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGameOverlay_1.32.17005.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGameOverlay_1.32.17005.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGameOverlay_1.32.17005.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_2.26.14003.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_2.26.14003.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_2.26.14003.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_2.26.14003.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxIdentityProvider_12.50.6001.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxIdentityProvider_12.50.6001.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.YourPhone_0.0.13313.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.YourPhone_0.0.13313.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.YourPhone_0.0.13313.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.YourPhone_2018.1128.231.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.18111.17311.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.18111.17311.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.18111.17311.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.18111.17311.0_neutral_split.scale-100_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.18111.17311.0_neutral_split.scale-125_8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneVideo_10.18111.17311.0_x64__8wekyb3d8bbwe
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.ZuneVideo_2019.18111.17311.0_neutral_~_8wekyb3d8bbwe
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.asynctextservice_8wekyb3d8bbwe_3d79f655ade1fc1f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.asynctextservice_8wekyb3d8bbwe_assets_5cf354e3143c045e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.asynctextservice_8wekyb3d8bbwe_pris_3cedd8e42975a683.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.ecapp_8wekyb3d8bbwe_ac10c70bb3589f82.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.ecapp_8wekyb3d8bbwe_assets_ae58e904a4695adf.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.ecapp_8wekyb3d8bbwe_pris_1fc7ac57a5ced560.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_43d095bdcce4e130.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_applicationguard_8359e7f74deb583c.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_booklibrary_3e904335483f7fff.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_bookviewer_990e8d61fcad5c14.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_bookviewer_css_38b1881b8abcd7a5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_bookviewer_js_78c5ff49aa9e261b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_contextmenu_6a54d142fb74801d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_dictionary_0a4f3c3a52411629.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_errorpages_73ec08ffb6105e23.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_f8075bc7ad02362b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_fonts_206f147a74e786c9.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_autoformfill_content_5091a4e29314f3d6.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_autoformfill_dcb3be839f31d5cd.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_autoformfill_document_3a04a7fa7c0c1008.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_autoformfill_prefill_578958a487bb2d19.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_learningtools_25cb263578b00eec.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_pinjsapi_85e7afd298d161a3.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_hostextensions_pinjsapi_content_bce4d61c88fff4ac.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_offlinetabs_7d551ad6791e5fc2.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_offlinetabs_offlinetabs_files_606f2d436ca9f85f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_persona_4fd2132d4ad15439.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_readingview_css_3066d24b0856bea1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_readingview_e64e82231b0e5fce.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_assets_webnotes_febc6b7abccb2874.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_en-us_assets_applicationguard_fd7778a67cb80f70.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_en-us_assets_errorpages_9b00dcea3e56c3f5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_en-us_assets_offlinetabs_d9769c7922380476.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedge_8wekyb3d8bbwe_pris_4719a634d2c04eec.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_7c54d2a38f4a267b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_controls_231926087bfb24b3.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_controls_listcontrol_eef1e9f6cc02fe9c.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_dommutations_bcd1772e3aeea97b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_dommutations_images_ba4ff6f874a9edb1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_editor_6e5693f2911e8b00.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_external_25adc88278dc605c.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_formatter_c8a6147a8388b7fb.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_formatter_css_7581a4e8169f757e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_formatter_html_64972c0dbcaefc6e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_formatter_typescript_13617520d76f3fac.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_grid_6c4c834909422a5d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_images_74ac0f6e88918dd1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_images_colorpicker_e8c4095bbb47dc9c.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_intellisense_721db7d304085d2e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_jquery_76027b9686fc0651.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_modelview_68ab429493cd05f1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_81919faf0ad34c24.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_836d0bedf622f96e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_039e33851d5947ad.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_bas_53a9eb248d463f89.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_bas_7aeda93bec9377b0.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_bas_b1551e46af82ed02.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_bas_f2dc8cf7872a49df.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_edi_78ddde63e2dab0fa.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_95fdc9aeaaab6af6.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_b3bb6a206b246432.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_b3bb6b0a6b24624b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_cfd623421b2d89d0.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_cfd626ca1b2d84ad.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_ec5dc157ad6c2803.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_monaco-editor_min_vs_lan_eebfb637d5a00776.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_objectview_212bfb620eb6c4fb.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_perftools_4757a4fe44691a93.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_perftools_controls_ca0aefc3c1cf16ed.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_perftools_images_a51757acdeb17b07.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_remote_86e6a9426c617031.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_resourcesview_cb7043508efcf9d9.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_slickgrid_03235f7c2ba7bcf3.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_slickgrid_plugins_58362696fb879581.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_common_tabcontrol_f71334f0c01c2e5f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_console_7c54de03bd35687d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_81168649365dfec5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_breakpoints_af355a13795264e7.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_breakpoints_images_4880219d231e1c07.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_callstack_633aff4012f6a965.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_callstack_images_9306b1fde7cddd57.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_cursor_11aa146906c830c9.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_cursor_images_ba8eeae0d1df5481.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_images_11b5f8b3068a4e7f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_languageservice_32e32ad1556f94fc.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_languageservice_images_1b734cca58996f4e.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_remote_11c812e70631185f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_watches_1bb8fcf67725ae40.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_debugger_watches_images_df31852dca1c5088.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_domtree_78a1d1c302cf8918.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_f226e3a6fa163210.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_images_77e98dbd64fdb0a6.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_styles_768f421567e95a56.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_styles_changesview_3db702d077f4d0ac.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_styles_styleview_88bd78c42d6d2ad0.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_dom_styles_winningview_ed97ab3258420ac1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_elements_71ccc64b4d409b7d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_emulation_fababcde97c7d402.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_emulation_remote_1475c96e2f3f2e62.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_f12host_7bac9fd7bf1afefb.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_frontend_739b19554a8c20f2.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_frontend_host_api_data_ed750ad946fce5e8.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_header_7b8c91c59139b693.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_header_images_fb78fc5c5a0cc765.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_header_remote_0db396303ddca9c5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_memoryanalyzer_de20a234bbe7c54f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_memoryanalyzer_images_b1ecedba4965354b.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_7ab47f47c1114fce.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_common_1658cff9c037a11d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_common_external_7f92c7900210e5ac.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_images_157c8fe3c2302ad8.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_remote_1428492fc551de78.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_network_styles_1422443bc51bd488.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_pluginhost_7855451f8cc6d5e5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_popup_1a69c5f1c3ce09d6.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_7a244bd9946463d6.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_console_d9535ed0236baa7f.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_emulation_591aa5980a836822.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_memoryanalyzer_501acfeebbf2699d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_network_efaedd2e00b02226.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_serviceworker_353d4d6caf0180b1.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_remote_storage_f70892c1f75cfbcb.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_serviceworker_a9f39a038cc3b7a3.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_serviceworker_images_6510545beb249a55.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_serviceworker_remote_55dc7b5801fb6335.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_storage_7a1e52c1c21a9b31.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_storage_images_1340465dd71e167d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_storage_remote_11ebffa9da3fca1d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_31c45221d4cb849d.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_images_b2ea4b46687fb713.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_js_a8f01f5afa26d7fe.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_js_controls_1157de3cb46e4242.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_js_cpuusage_1243fe54b3c33ef5.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_23_visualprofiler_js_hubgraphs_1e54f4890cd85af2.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_9e9a8bf16c9ce6fb.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.microsoftedgedevtoolsclient_8wekyb3d8bbwe_pris_54732ccdf1f56e95.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.windows.narratorquickstart_8wekyb3d8bbwe_aa4229d57e07074a.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.windows.narratorquickstart_8wekyb3d8bbwe_assets_3c2c27c2cd8c0a67.cdf-ms
DEL /F /Q C:\Windows\WinSxS\FileMaps\$$_systemapps_microsoft.windows.narratorquickstart_8wekyb3d8bbwe_pris_2fcc74e35c7bd23c.cdf-ms
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.bingweather_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.desktopappinstaller_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.gethelp_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.getstarted_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.heifimageextension_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.messaging_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.microsoft3dviewer_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.microsoftofficehub_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.microsoftsolitairecollection_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.microsoftstickynotes_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.mixedreality.portal_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.mspaint_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.office.onenote_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.oneconnect_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.people_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.print3d_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.screensketch_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.storepurchaseapp_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.vp9videoextensions_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.wallet_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.webmediaextensions_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.webpimageextension_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windows.photos_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowsalarms_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowscalculator_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowscamera_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowscommunicationsapps_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowsfeedbackhub_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowsmaps_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowssoundrecorder_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.windowsstore_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xbox.tcui_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xboxapp_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xboxgameoverlay_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xboxgamingoverlay_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xboxidentityprovider_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.xboxspeechtotextoverlay_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.yourphone_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.zunemusic_8wekyb3d8bbwe.xml
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.zunevideo_8wekyb3d8bbwe.xml
