RD /S /Q C:\Windows\WinSxS\amd64_microsoft-windows-skype-ortc_31bf3856ad364e35_10.0.18362.1_none_bc54841acbdeb4f5
RD /S /Q "C:\Program Files\WindowsApps\Microsoft.SkypeApp_14.35.152.0_neutral_~_kzf8qxf38zg5c
RD /S /Q C:\Windows\WinSxS\wow64_microsoft-windows-skype-ortc_31bf3856ad364e35_10.0.18362.1_none_c6a92e6d003f76f0
DEL /F /Q C:\Windows\WinSxS\Manifests\amd64_microsoft-windows-skype-ortc_31bf3856ad364e35_10.0.18362.1_none_bc54841acbdeb4f5.manifest
DEL /F /Q C:\ProgramData\Microsoft\Windows\ClipSVC\Install\Apps\microsoft.skypeapp_kzf8qxf38zg5c.xml
DEL /F /Q C:\ProgramData\Microsoft\UEV\InboxTemplates\MicrosoftSkypeForBusiness2016Win32.xml
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-a..gement-uevtemplates_31bf3856ad364e35_10.0.18362.1_none_29d317c0535e42ae\MicrosoftSkypeForBusiness2016Win32.xml
DEL /F /Q C:\ProgramData\Microsoft\UEV\InboxTemplates\MicrosoftSkypeForBusiness2016Win64.xml
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-windows-a..gement-uevtemplates_31bf3856ad364e35_10.0.18362.1_none_29d317c0535e42ae\MicrosoftSkypeForBusiness2016Win64.xml
DEL /F /Q C:\Windows\SystemResources\Windows.UI.ShellCommon\StartUI\Assets\Fonts\SkypeUISymbol-Regular.ttf
DEL /F /Q C:\Windows\WinSxS\amd64_microsoft-composable-start-binaries_31bf3856ad364e35_10.0.18362.1_none_5b4cd39b2dfba852\SkypeUISymbol-Regular.ttf
DEL /F /Q C:\Windows\WinSxS\Manifests\wow64_microsoft-windows-skype-ortc_31bf3856ad364e35_10.0.18362.1_none_c6a92e6d003f76f0.manifest
